### ISSUE TITLE
Black Canvas after closing and reopening

### ISSUE THREAD

**Issue by MutterOberin** [inviwo/inviwo#298] opened 2018-11-14 16:49 UTC
### Steps:

* Drag a volume onto graph
* Create a raycaster
* Raycaster gets created, Canvas is open and shows data
* Close Canvas Window
* Open Canvas Window

Result: Black Window not showing anything.

### Workaround:

* Drag new Canvas replacing the old
* Works one time (until closed and reopened)

**Comment by petersteneteg** [comment] 2018-11-14 18:42
you can just double click on the canvas processor a couple of time and it will show again. This seems to be some bug in qt 5.11...

also duplicate of #251

**Closed as completed** 2018-11-14 18:43 UTC
Labels: A: Duplicate
