### ISSUE TITLE
Icon hover doesn't go away 

### ISSUE THREAD

**Issue by k1tesurfen** [inviwo/inviwo#449] opened 2019-03-07 15:22 UTC
**Issue**

Hovering over the toolbar icons shows light blue border, which sometimes does not disappear after moving the mouse away from the icon

**Steps to reproduce**

moving the mouse from below the icon over it and exiting the inviwo window.

here is a video of the bug
https://youtu.be/3EBu_TgxmJc

**Environment information**
* Operating System: macOS
cmake output:

-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.7.2", minimum required is "3")
-- C++17 enabled
-- pybind11 v2.2.4
-- Found PythonInterp: /usr/local/bin/python3 (found version "3.7.2")
-- Version: 5.2.2
-- Build type:
-- CXX_STANDARD: 17
-- ILMBASE_PACKAGE_PREFIX = /usr/local
-- Skipping build of b44ExpLogTable.h
-- Skipping build of dwaLookups.h
-- Shared libraries enabled
-- Checking for module 'minizip'
--   No package 'minizip' found
-- Could NOT find rt (missing: RT_LIBRARY)
INFO RT-extension not found. glTF import/export will be built without Open3DGC-compression.
-- Enabled formats: AMF 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD STEP
-- Disabled formats:
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
-- Using Cocoa for window creation
-- Could NOT find Filesystem (missing: filesystem_headers_found filesystem_can_link)
-- Will not build Inviwo meta since the used compiler does not have c++ filesystem support
-- Configure started at 2019-03-07 14:53:01 and ended at 2019-03-07 14:53:05
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   assimp
   gtest
   gtest_main

**Comment by martinfalk** [comment] 2019-03-08 16:59
Cannot reproduce on Windows. Even with fast mouse movements.
Appears to be a OSX specific Qt-bug. Maybe related to how Qt uses stylesheets.

**Comment by martinfalk** [comment] 2019-07-16 15:17
Closing this for now.

**Closed as completed by martinfalk** 2019-07-16 15:17 UTC
Labels: T: Bug, S: OSX
