### ISSUE TITLE
Crash in Rasterization Renderer when disconnecting optional background inport

### ISSUE THREAD

**Issue by r-englund** [inviwo/inviwo#955] opened 2020-06-12 09:35 UTC
Probably caused by `imageInport_->getData()` return nullptr in the code refrenced below: 

https://github.com/inviwo/inviwo/blob/d1749ba220ba089cc78391da222461e38ad40bd4/modules/meshrenderinggl/src/processors/rasterizationrenderer.cpp#L114-L115

**Comment by AnkeAnke** [comment] 2020-06-12 15:56
You're right, it was caused by that code line - thanks! Fixed in PR.

**Closed as completed** 2020-06-13 15:47 UTC
Labels: T: Bug
